# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a6948ade3e32682bf82d29a4f6ca092a457f8220b0dd417798c7b541cebcae59c97067f4c731193c19a6a318dcfc0bd2861dd1937658a0fd28e16a5884f628a

test:
  secret_key_base: 2a1a18e4367c023853cc19c4b3c689fa6b7a98f823df896cb7993ddc6f222fb8c733015a25d8ce4f33379b29097ded75898845d7d5afccde54013f2e98587186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
